// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zilhazcjtdmfmqchqubx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppbGhhemNqdGRtZm1xY2hxdWJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Njg3MzksImV4cCI6MjA2OTQ0NDczOX0.xPgtWiEq4vgEp5xME9SGGx22xQc1DjTkWkausw660e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});